// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass DummyMuxyControl : Windows.UI.Xaml.Controls.StackPanel
    {
        DummyMuxyControl();
    }
}
