// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass TabWinRT
	{
        TabWinRT(winrt::Guid& profile, winrt::Microsoft::Terminal::TerminalControl::TermControl& control);
    }
}
