// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "../ConvertedTab.idl";

namespace TerminalApp
{
    delegate void LastTabClosedEventArgs();
    delegate void ToggleFullscreenEventArgs();

    [default_interface] runtimeclass TerminalPage : Windows.UI.Xaml.Controls.Page
    {
        TerminalPage();

        event Windows.Foundation.TypedEventHandler<Object, String> TitleChanged;
        event Windows.Foundation.TypedEventHandler<Object, LastTabClosedEventArgs> LastTabClosed;
        event Windows.Foundation.TypedEventHandler<Object, Windows.UI.Xaml.UIElement> SetTitleBarContent;
        event Windows.Foundation.TypedEventHandler<Object, Windows.UI.Xaml.Controls.ContentDialog> ShowDialog;
        event Windows.Foundation.TypedEventHandler<Object, ToggleFullscreenEventArgs> ToggleFullscreen;

        Microsoft.UI.Xaml.Controls.TabView TabView { get; };

        Windows.Foundation.Collections.IObservableVector<ConvertedTab> ConvertedTabs { get; };
    }
}
